name: Node.js CI

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          # update the Node version to meet your needs
          node-version: latest
          cache: npm

      - name: Build
        run: |
          npm ci
          npm run build
          npm run export
          touch out/.nojekyll
      - name: Deploy
        uses: OskarArslanov/oskararslanov.github.io@master
        with:
          branch: gh-pages
          folder: out
        # configure an external GitHub Pages deploy workflow here
