name: GitHub Pages deploy

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 19.9
        uses: actions/setup-node@v3
        with:
          node-version: '19.9'
          cache: npm
      - name: Build
        run: |
          npm ci
          npm run build
          npm run export
          touch out/.nojekyll
      - name: Deploy
        uses: OskarArslanov/oskararslanov.github.io@master
        # uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: master
          folder: out
        # configure an external GitHub Pages deploy workflow here
